# Generated by Django 4.1.2 on 2022-10-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstorage', '0002_remove_profilepicture_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image_name',
            field=models.CharField(default='profile_pic_<built-in method now of type object at 0x00007FF84D72C650>', max_length=255),
        ),
    ]
