# Generated by Django 4.1.2 on 2022-10-19 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstorage', '0006_alter_profilepicture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
