# Generated by Django 4.1.2 on 2022-10-19 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstorage', '0008_alter_profilepicture_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='image_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png', 'bmp'])]),
        ),
    ]
