# Generated by Django 4.1.2 on 2022-10-20 03:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloudstorage', '0009_alter_profilepicture_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('music_file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['m4a', 'mp3', 'wav', 'aac', 'flac', 'alac', 'aiff', 'ogg', 'wma'])])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
