# Generated by Django 4.1.2 on 2022-10-21 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloudstorage', '0012_alter_musicsample_music_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_sample', to=settings.AUTH_USER_MODEL),
        ),
    ]
