# Generated by Django 4.1.2 on 2022-10-11 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 2, 0, 32, 666413, tzinfo=datetime.timezone.utc)),
        ),
    ]
