# Generated by Django 4.1.2 on 2022-10-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_genre'),
        ('instruments', '0002_alter_instrument_name'),
        ('profiles', '0004_experiencelevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genres',
            field=models.ManyToManyField(blank=True, to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instruments',
            field=models.ManyToManyField(blank=True, through='profiles.UserExperienceLevel', to='instruments.instrument'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level_of_commitment',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seeking',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
