# Generated by Django 4.1.2 on 2022-10-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_gender_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencelevel',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
