# Generated by Django 4.1.2 on 2022-10-13 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_name'),
        ('profiles', '0008_commitmentlevel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExperienceLevel',
            new_name='UserInstrument',
        ),
    ]
