# Generated by Django 4.1.2 on 2022-10-13 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_userexperiencelevel_userinstrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstrument',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinstruments', to='profiles.userprofile'),
        ),
    ]
