# Generated by Django 4.1.2 on 2022-10-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_userinstrument_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
