# Generated by Django 4.1.2 on 2022-10-13 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_gender_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
