# Generated by Django 4.1.2 on 2022-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_userprofile_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
