# Generated by Django 4.1.2 on 2022-10-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_url',
        ),
    ]
