# Generated by Django 4.1.2 on 2022-10-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_userprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
