# Generated by Django 4.1.2 on 2022-11-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_name'),
        ('profiles', '0022_alter_socialmedialink_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='seeking',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seeking',
            field=models.ManyToManyField(blank=True, related_name='user_profile_seeking', to='instruments.instrument'),
        ),
    ]
