# Generated by Django 4.1.2 on 2022-10-12 00:18

import backend.shared
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=backend.shared.LowerCaseCharField(max_length=50),
        ),
    ]
