# Generated by Django 4.1.2 on 2022-10-13 01:48

import backend.shared
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=backend.shared.LowerCaseCharField(max_length=50, unique=True),
        ),
    ]
